### ISSUE TITLE
php7

### ISSUE THREAD

**Issue by cordoval** [tutumcloud/apache-php#21]
i have good experience with how you setup the basic apache-php together

can you update this to php7? would be wonderful

**Comment by OscarBarrett** [comment]
Tutum has shut down as of May 31st 2016 (they were acquired by Docker), so I don't think their images will be getting updated at all.

I've created a php7 version here: https://github.com/OscarBarrett/apache-php7
`obarrett/apache-php7` on Docker Hub.

**Comment by cordoval** [comment]
i already created my own php7 fpm nginx image, closing this as it is no longer needed, thanks
